import base64
import io

import cv2
import numpy as np
from flask import Flask, request
from joblib import load
import pymysql
from pathlib import Path
from PIL import Image as PILImage

from database import DB_CONNECTION_ERROR, connection, cursor
from feature_extractor import extract_features
# preprocess_text uses scam_detector.ipynb's Section 3.2 cleaning
# (lowercase, URL/phone/money tokenising, stopword removal, lemmatization)
# so the raw message gets turned into the same token format text_tfidf.pkl
# was fitted on.
from text_feature_extractor import preprocess as preprocess_text
from gemini_explainer import (
    generate_explanation,
    generate_deepfake_explanation,
    generate_text_explanation,  # writes the text-extractor explanation
    translate_to_english,       # translates non-English input before classification
    extract_text_from_image,    # transcribes SMS screenshots for the text extractor
)

MODEL_PATH = Path(__file__).resolve().with_name("phishing_model.pkl")
model = load(MODEL_PATH)
app = Flask(__name__)

# ── Text extractor model ──────────────────
#
# The text extractor's two artifacts - the fitted TF-IDF vectorizer and the trained
# soft-voting ensemble - are generated by running scam_detector.ipynb's
# Section 6 export cell, and won't exist yet. Loading
# them lazily means the whole Flask app can still start up and serve
# the phishing/deepfake routes normally even before that notebook cell has
# ever been run - only /detect-text itself will fail until the .pkl files are there.
TEXT_MODEL_PATH = Path(__file__).resolve().with_name("text_model.pkl")
TEXT_TFIDF_PATH = Path(__file__).resolve().with_name("text_tfidf.pkl")

# Module-level caches so the two .pkl files are only ever read from disk
# once per server process, not on every single request.
_text_model = None
_text_tfidf = None


def _get_text_model():
    """
    Returns the (model, vectorizer) tuple, loading them from disk on first
    call and reusing the cached objects on every call afterwards.

    Raises FileNotFoundError - rather than crashing the whole Flask process
    with an unhandled exception - if the export cell hasn't been run,
    the /detect-text (the only caller) can catch it and return a helpful
    503 response instead of crashing the entire backend.
    """
    global _text_model, _text_tfidf
    if _text_model is None or _text_tfidf is None:
        if not TEXT_MODEL_PATH.exists() or not TEXT_TFIDF_PATH.exists():
            raise FileNotFoundError(
                "Text extractor model files not found. Run the export cell in "
                "scam_detector.ipynb (Section 6) to generate text_model.pkl and text_tfidf.pkl."
            )
        _text_model = load(TEXT_MODEL_PATH)
        _text_tfidf = load(TEXT_TFIDF_PATH)
    return _text_model, _text_tfidf

# ── Deepfake detector (lazy-loaded on first request) ────────────────────────────
_deepfake_detector = None
_deepfake_sessions: dict = {}
_deepfake_reasons: dict = {}  # {session_id: {"verdict": str, "reason": str}}


def _get_deepfake_detector():
    global _deepfake_detector
    if _deepfake_detector is None:
        from jing_model import Detector  # heavy import — only once
        _deepfake_detector = Detector()
    return _deepfake_detector


def ensure_db_ready():
    if connection is None or cursor is None:
        return {
            "error": f"Database unavailable. Check DB credentials/config. Details: {DB_CONNECTION_ERROR}"
        }, 503
    return None


@app.after_request
def add_cors_headers(response):
    response.headers["Access-Control-Allow-Origin"] = "*"
    response.headers["Access-Control-Allow-Headers"] = "Content-Type,Authorization"
    response.headers["Access-Control-Allow-Methods"] = "GET,POST,OPTIONS"
    return response


@app.route("/")
def home():
    return {"message": "Backend Working"}


@app.route("/signup", methods=["POST", "OPTIONS"])
def signup():
    if request.method == "OPTIONS":
        return "", 204

    data = request.get_json(silent=True) or {}

    required_fields = ["username", "email", "password", "role"]
    missing = [field for field in required_fields if not data.get(field)]
    if missing:
        return {"error": f"Missing required fields: {', '.join(missing)}"}, 400

    db_error = ensure_db_ready()
    if db_error:
        return db_error

    username = data["username"]
    email = data["email"]
    password = data["password"]
    role = data["role"]

    try:
        cursor.execute(
            """
            INSERT INTO users
            (username,email,password,role)

            VALUES
            (%s,%s,%s,%s)
            """,
            (username, email, password, role),
        )
        connection.commit()
        return {"message": "success"}
    except pymysql.err.IntegrityError:
        connection.rollback()
        return {"error": "Email already exists."}, 409
    except Exception as exc:
        connection.rollback()
        return {"error": f"Signup failed: {str(exc)}"}, 500


@app.route("/login", methods=["POST", "OPTIONS"])
def login():
    if request.method == "OPTIONS":
        return "", 204

    db_error = ensure_db_ready()
    if db_error:
        return db_error

    data = request.json

    email = data["email"]
    password = data["password"]

    cursor.execute(
        """
        SELECT *
        FROM users
        WHERE email=%s
        AND password=%s
        """,
        (email, password),
    )

    user = cursor.fetchone()

    if user:
        return {
            "success": True,
            "role": user[4],
            "user_id": user[0],
        }

    return {
        "success": False,
    }


@app.route("/detect", methods=["POST", "OPTIONS"])
def detect():
    if request.method == "OPTIONS":
        return "", 204

    db_error = ensure_db_ready()
    if db_error:
        return db_error

    data = request.json
    url = data["url"]

    features = extract_features(url)
    prediction = model.predict([features])

    try:
        confidence = float(max(model.predict_proba([features])[0]))
    except AttributeError:
        confidence = None

    if prediction[0] == 1:
        result = "Legitimate Website"
    else:
        result = "Phishing Website"

    cursor.execute(
        """
        INSERT INTO detections
        (url,result)

        VALUES
        (%s,%s)
        """,
        (url, result),
    )
    connection.commit()

    explanation_result = generate_explanation(url, result, confidence)

    return {
        "result": result,
        "confidence": confidence,
        "explanation": explanation_result["explanation"],
        "explanation_available": explanation_result["available"],
    }


@app.route("/detect-text", methods=["POST", "OPTIONS"])
def detect_text():
    """
    The Text Extractor's main endpoint. Given a raw SMS/message string,
    this runs the following:

      1. Translation (translate_to_english) - returns the
         message unchanged if it's already English, or a Gemini-translated
         English version if it isn't. This happens before classification, as the model below only understands English.
      2. Preprocessing (preprocess_text) - the same lowercase/tokenise/
         lemmatize pipeline used when the model was trained, so the text
         is in the format the vectorizer expects.
      3. Vectorization + prediction (text_tfidf.transform +
         text_model.predict) - turns the cleaned text into the TF-IDF
         feature vector the ensemble was trained on, then classifies it.
      4. Explanation (generate_text_explanation) - a separate Gemini call
         that writes an explanation for the verdict the model
         already produced in step 3.

    Translation and explanation are two independent Gemini calls
    as translation has to complete before classification can even run, while the explanation depends on
    classification's result.
    """
    if request.method == "OPTIONS":
        return "", 204

    data = request.get_json(silent=True) or {}
    message = data.get("message", "")
    user_id = data.get("user_id")

    if not message or not message.strip():
        return {"error": "No message provided"}, 400

    try:
        text_model, text_tfidf = _get_text_model()
    except FileNotFoundError as exc:
        # Surfaced as a 503 rather than a 500, since this is a recoverable state.
        return {"error": str(exc)}, 503

    # Step 1: translate- the model
    # was trained only on English SMS text, so classification always runs
    # on the English version of the message.
    translation = translate_to_english(message)
    english_message = translation["text"]

    # Steps 2-3: clean the (now-English) text and run it through the
    # trained TF-IDF vectorizer + soft-voting ensemble exported from the
    # notebook.
    cleaned = preprocess_text(english_message)
    vector = text_tfidf.transform([cleaned])
    prediction = text_model.predict(vector)

    try:
        # predict_proba returns [P(legitimate), P(scam)] for each row; the
        # larger of the two is reported as the model's confidence in
        # whichever class it actually predicted.
        confidence = float(max(text_model.predict_proba(vector)[0]))
    except AttributeError:
        # In case a future model swap uses a classifier
        # without predict_proba,the app should still work, just without a confidence percentage.
        confidence = None

    # label encoding matches the notebook: 1 = spam/scam, 0 = ham/legitimate.
    if prediction[0] == 1:
        result = "Scam Message"
    else:
        result = "Legitimate Message"

    # Step 4: ask Gemini to explain the verdict above.
    explanation_result = generate_text_explanation(english_message, result, confidence)

    # Save this check to the user's history (Text Extractor only - the
    # phishing/deepfake tools have their own separate storage/no storage).
    # This is best-effort: if there's no user_id (not logged in) or the DB
    # is unavailable, the check still returns normally, it just isn't saved
    # and check_id comes back null - the frontend then simply can't show a
    # flag button or history entry for that particular check.
    check_id = None
    if user_id is not None and connection is not None and cursor is not None:
        try:
            cursor.execute(
                """
                INSERT INTO text_checks
                (user_id, message, result, confidence)

                VALUES
                (%s, %s, %s, %s)
                """,
                (user_id, message, result, confidence),
            )
            connection.commit()
            check_id = cursor.lastrowid
        except Exception:
            connection.rollback()

    return {
        "result": result,
        "confidence": confidence,
        "explanation": explanation_result["explanation"],
        "explanation_available": explanation_result["available"],
        # The frontend only renders the "Translated to English" box when
        # `translated` is true - for English input this stays false and
        # translated_text is null, so nothing extra is shown.
        "translated": translation["was_translated"],
        "translated_text": english_message if translation["was_translated"] else None,
        "detected_language": translation["detected_language"],
        # id of the saved text_checks row, used by the frontend to flag/delete
        # this specific check later - null if it couldn't be saved.
        "check_id": check_id,
    }


@app.route("/extract-text-from-image", methods=["POST", "OPTIONS"])
def extract_text_from_image_route():
    """
    Text Extractor's screenshot-upload endpoint. Given a base64-encoded
    image of an SMS/chat screenshot, this only transcribes the message text
    via Gemini vision (extract_text_from_image) - it does NOT classify
    anything. The frontend drops the returned text into the same textarea
    used for pasted messages, lets the user review/edit it, and classification
    still happens through the existing /detect-text flow when they click
    "Check Message". Kept as a separate endpoint so /detect-text's
    translate -> preprocess -> vectorize -> predict pipeline is untouched.
    """
    if request.method == "OPTIONS":
        return "", 204

    data = request.get_json(silent=True) or {}
    image_b64 = data.get("image", "")
    mime_type = data.get("mime_type") or "image/jpeg"

    if not image_b64:
        return {"error": "No image provided"}, 400

    # Accept both raw base64 and data URLs (e.g. "data:image/png;base64,....").
    if "," in image_b64 and image_b64.strip().lower().startswith("data:"):
        header, image_b64 = image_b64.split(",", 1)
        if "image/" in header:
            mime_type = header.split(";")[0].replace("data:", "") or mime_type

    try:
        image_bytes = base64.b64decode(image_b64)
    except Exception:
        return {"error": "Invalid image data"}, 400

    extraction = extract_text_from_image(image_bytes, mime_type)

    if not extraction["available"]:
        return {"error": extraction["error"] or "Could not extract text from that screenshot."}, 422

    return {"text": extraction["text"]}


@app.route("/text-checks", methods=["GET", "OPTIONS"])
def list_text_checks():
    """
    Text Extractor's "recent checks" history for one user. `user_id` is
    passed as a query param (?user_id=123) rather than requiring a full auth
    header, matching the rest of this app's lightweight, session-token-free
    auth model (see /login above).
    """
    if request.method == "OPTIONS":
        return "", 204

    db_error = ensure_db_ready()
    if db_error:
        return db_error

    user_id = request.args.get("user_id")
    if not user_id:
        return {"error": "user_id is required"}, 400

    cursor.execute(
        """
        SELECT id, message, result, confidence, flagged, created_at
        FROM text_checks
        WHERE user_id=%s
        ORDER BY created_at DESC
        LIMIT 50
        """,
        (user_id,),
    )
    rows = cursor.fetchall()

    checks = [
        {
            "id": row[0],
            "message": row[1],
            "result": row[2],
            "confidence": row[3],
            "flagged": bool(row[4]),
            "created_at": row[5].isoformat() if row[5] else None,
        }
        for row in rows
    ]

    return {"checks": checks}


@app.route("/text-checks/<int:check_id>/flag", methods=["POST", "OPTIONS"])
def flag_text_check(check_id):
    """
    Marks one text_checks row as "flagged as wrong" by its owner. Enforces
    "one flag per check" server-side - `UPDATE ... WHERE id=%s AND
    user_id=%s AND flagged=FALSE` only ever affects a row the very first
    time it's flagged (rowcount is 0 on every call after that, or if the
    check belongs to someone else), so replaying this request can't spam
    flags on the same row or flag another user's check.
    """
    if request.method == "OPTIONS":
        return "", 204

    db_error = ensure_db_ready()
    if db_error:
        return db_error

    data = request.get_json(silent=True) or {}
    user_id = data.get("user_id")
    if not user_id:
        return {"error": "user_id is required"}, 400

    cursor.execute(
        """
        UPDATE text_checks
        SET flagged=TRUE
        WHERE id=%s AND user_id=%s AND flagged=FALSE
        """,
        (check_id, user_id),
    )
    connection.commit()

    if cursor.rowcount == 0:
        # Either this check doesn't belong to this user, doesn't exist, or
        # (most commonly) was already flagged once before.
        return {"error": "Check not found, not yours, or already flagged."}, 409

    return {"message": "flagged"}


@app.route("/text-checks/<int:check_id>", methods=["DELETE", "OPTIONS"])
def delete_text_check(check_id):
    """
    Deletes one text_checks row - only the row's own user can delete it.
    `user_id` is required in the query string so a user can't delete another
    user's history entry just by guessing an id.
    """
    if request.method == "OPTIONS":
        return "", 204

    db_error = ensure_db_ready()
    if db_error:
        return db_error

    user_id = request.args.get("user_id")
    if not user_id:
        return {"error": "user_id is required"}, 400

    cursor.execute(
        "DELETE FROM text_checks WHERE id=%s AND user_id=%s",
        (check_id, user_id),
    )
    connection.commit()

    if cursor.rowcount == 0:
        return {"error": "Check not found or not yours."}, 404

    return {"message": "deleted"}


@app.route("/admin/stats", methods=["GET", "OPTIONS"])
def admin_stats():
    if request.method == "OPTIONS":
        return "", 204

    db_error = ensure_db_ready()
    if db_error:
        return db_error

    cursor.execute("SELECT COUNT(*) FROM users")
    total_users = cursor.fetchone()[0]

    cursor.execute(
        """
        SELECT COUNT(*)
        FROM detections
        WHERE result='Phishing Website'
        """
    )
    total_scams = cursor.fetchone()[0]

    return {
        "total_users": total_users,
        "total_scams": total_scams,
    }


@app.route("/deepfake/score", methods=["POST", "OPTIONS"])
def deepfake_score():
    if request.method == "OPTIONS":
        return "", 204

#Read JSON data from the request
    data = request.get_json(silent=True) or {}
    frame_b64 = data.get("frame")
    session_id = data.get("session_id", "default")
    reset = data.get("reset", False)

    if not frame_b64:
        return {"error": "No frame provided"}, 400

    try:
        img_bytes = base64.b64decode(frame_b64)
        img = PILImage.open(io.BytesIO(img_bytes)).convert("RGB")
        frame_rgb = np.array(img)
    except Exception as exc:
        return {"error": f"Invalid frame data: {exc}"}, 400

    try:
        detector = _get_deepfake_detector()
    except Exception as exc:
        return {"error": f"Model unavailable: {exc}"}, 503

    try:
        frame_result = detector.score_frame(frame_rgb)
    except Exception as exc:
        return {"error": f"Frame scoring failed: {exc}"}, 500

    from jing_model import RollingVerdict
    if reset or session_id not in _deepfake_sessions:
        _deepfake_sessions[session_id] = RollingVerdict(window=25)

    rolling = _deepfake_sessions[session_id].update(
        frame_result["prob"], frame_result["face_found"]
    )

    # ── Debug logging ────────────────────────────────────────────────────────────
    print(
        f"[score] frame_prob={frame_result['prob']:.4f} frame_verdict={frame_result['verdict']}"
        f" | rolling_prob={rolling['prob']:.4f} rolling_verdict={rolling['verdict']}"
        f" | frames_in_window={rolling['frames_in_window']}"
    )
    # ── End debug ────────────────────────────────────────────────────────────────

    # ── LLM explanation (generated only when the verdict changes) ────────────────
    current_verdict = rolling["verdict"]
    cached = _deepfake_reasons.get(session_id)
    if cached is None or cached["verdict"] != current_verdict:
        reason = generate_deepfake_explanation(
            verdict=current_verdict,
            prob=rolling["prob"],
            face_found=frame_result["face_found"],
            frames_in_window=rolling["frames_in_window"],
            frame_prob=frame_result["prob"],
            max_prob=rolling["max_prob"],
            min_prob=rolling["min_prob"],
            deepfake_frames=rolling["deepfake_frames"],
            real_frames=rolling["real_frames"],
        )
        _deepfake_reasons[session_id] = {"verdict": current_verdict, "reason": reason}
    else:
        reason = cached["reason"]
    # ── End LLM explanation ───────────────────────────────────────────────────────

    return {
        "frame": frame_result,
        "rolling": rolling,
        "reason": reason,
    }


@app.route("/deepfake/heatmap", methods=["POST", "OPTIONS"])
def deepfake_heatmap():
    if request.method == "OPTIONS":
        return "", 204

    data = request.get_json(silent=True) or {}
    frame_b64 = data.get("frame")
    session_id = data.get("session_id", "default")

    if not frame_b64:
        return {"error": "No frame provided"}, 400

    try:
        img_bytes = base64.b64decode(frame_b64)
        img = PILImage.open(io.BytesIO(img_bytes)).convert("RGB")
        frame_rgb = np.array(img)
    except Exception as exc:
        return {"error": f"Invalid frame data: {exc}"}, 400

    try:
        detector = _get_deepfake_detector()
    except Exception as exc:
        return {"error": f"Model unavailable: {exc}"}, 503

    try:
        result = detector.score_frame_with_heatmap(frame_rgb)
    except Exception as exc:
        return {"error": f"Heatmap scoring failed: {exc}"}, 500

    from jing_model import RollingVerdict
    if session_id not in _deepfake_sessions:
        _deepfake_sessions[session_id] = RollingVerdict(window=25)

    rolling = _deepfake_sessions[session_id].update(
        result["prob"], result["face_found"]
    )

    current_verdict = rolling["verdict"]
    cached = _deepfake_reasons.get(session_id)
    if cached is None or cached["verdict"] != current_verdict:
        reason = generate_deepfake_explanation(
            verdict=current_verdict,
            prob=rolling["prob"],
            face_found=result["face_found"],
            frames_in_window=rolling["frames_in_window"],
            frame_prob=result["prob"],
            max_prob=rolling["max_prob"],
            min_prob=rolling["min_prob"],
            deepfake_frames=rolling["deepfake_frames"],
            real_frames=rolling["real_frames"],
        )
        _deepfake_reasons[session_id] = {"verdict": current_verdict, "reason": reason}
    else:
        reason = cached["reason"]

    # Encode face-crop RGBA as PNG only on Grad-CAM frames (None on throttled frames).
    # The frontend re-uses its cached heatmap image and repositions it via bbox,
    # decoupling visual render rate (30 fps rAF) from backend compute rate.
    heatmap_b64 = None
    if result.get("heatmap_rgba") is not None:
        buf = io.BytesIO()
        PILImage.fromarray(result["heatmap_rgba"], "RGBA").save(buf, format="PNG")
        heatmap_b64 = base64.b64encode(buf.getvalue()).decode()

    # Normalize bbox to [0-1] fractions of the received frame so the frontend
    # can correctly map it back regardless of the capture resolution sent.
    raw_bbox = result.get("bbox")
    if raw_bbox is not None:
        fh, fw = frame_rgb.shape[:2]
        bbox_norm = [raw_bbox[0] / fw, raw_bbox[1] / fh,
                     raw_bbox[2] / fw, raw_bbox[3] / fh]
    else:
        bbox_norm = None

    return {
        "frame": {
            "prob": result["prob"],
            "verdict": result["verdict"],
            "face_found": result["face_found"],
        },
        "rolling": rolling,
        "reason": reason,
        "heatmap": heatmap_b64,
        "bbox": bbox_norm,
    }


@app.route("/deepfake/stylized_heatmap", methods=["POST", "OPTIONS"])
def deepfake_stylized_heatmap():
    if request.method == "OPTIONS":
        return "", 204

    data = request.get_json(silent=True) or {}
    frame_b64 = data.get("frame")
    session_id = data.get("session_id", "default")

    if not frame_b64:
        return {"error": "No frame provided"}, 400

    try:
        img_bytes = base64.b64decode(frame_b64)
        img = PILImage.open(io.BytesIO(img_bytes)).convert("RGB")
        frame_rgb = np.array(img)
    except Exception as exc:
        return {"error": f"Invalid frame data: {exc}"}, 400

    try:
        detector = _get_deepfake_detector()
    except Exception as exc:
        return {"error": f"Model unavailable: {exc}"}, 503

    try:
        result = detector.score_frame_with_stylized_heatmap(frame_rgb)
    except Exception as exc:
        return {"error": f"Stylized heatmap scoring failed: {exc}"}, 500

    from jing_model import RollingVerdict
    if session_id not in _deepfake_sessions:
        _deepfake_sessions[session_id] = RollingVerdict(window=25)

    prob = result["prob"]
    face_found = result["face_found"]

    # prob is None when no face was detected — skip rolling update in that case
    if prob is not None:
        rolling = _deepfake_sessions[session_id].update(prob, face_found)
        current_verdict = rolling["verdict"]
        cached = _deepfake_reasons.get(session_id)
        if cached is None or cached["verdict"] != current_verdict:
            reason = generate_deepfake_explanation(
                verdict=current_verdict,
                prob=rolling["prob"],
                face_found=face_found,
                frames_in_window=rolling["frames_in_window"],
                frame_prob=prob,
                max_prob=rolling["max_prob"],
                min_prob=rolling["min_prob"],
                deepfake_frames=rolling["deepfake_frames"],
                real_frames=rolling["real_frames"],
            )
            _deepfake_reasons[session_id] = {"verdict": current_verdict, "reason": reason}
        else:
            reason = cached["reason"]
    else:
        rolling = None
        reason = ""

    # Encode the already-composited BGR overlay as JPEG
    ok, buf = cv2.imencode(".jpg", result["heatmap_overlay_bgr"], [cv2.IMWRITE_JPEG_QUALITY, 85])
    heatmap_b64 = base64.b64encode(buf.tobytes()).decode() if ok else None

    return {
        "frame": {
            "prob": prob,
            "verdict": result["verdict"],
            "face_found": face_found,
        },
        "rolling": rolling,
        "reason": reason,
        "heatmap": heatmap_b64,
    }


@app.route("/deepfake/reset", methods=["POST", "OPTIONS"])
def deepfake_reset():
    if request.method == "OPTIONS":
        return "", 204
    data = request.get_json(silent=True) or {}
    session_id = data.get("session_id", "default")
    _deepfake_sessions.pop(session_id, None)
    _deepfake_reasons.pop(session_id, None)
    return {"message": "session reset"}


if __name__ == "__main__":
    app.run(debug=True)